version: '3.4'

services:
  ezstore.microservice.product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  microservice.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microservice.notification.backgroundprocess:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microservice.logging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microservice.logging.backgroundprocess:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

