version: '3.4'

services:
  microservice.identityserver:
    image: microservice.identity.server
    container_name: microservice-identity-server
    build:
      context: .
      dockerfile: 02.CoreServices/Member/Microservice.IdentityServer/Dockerfile
    ports:
      - 5001:80

  microservice.logging.api:
    image: microservice.logging.api
    container_name: microservice-logging-api
    build:
      context: .
      dockerfile: 02.CoreServices/Logging/Microservice.Logging.API/Dockerfile
    ports:
      - 5002:80

  microservice.notification.backgroundprocess:
    image: microservice.notification.background
    container_name: microservice-notification-background
    build:
      context: .
      dockerfile: 02.CoreServices/Notification/Microservice.Notification.BackgroundProcess/Dockerfile
    dns:
      - 8.8.8.8

  microservice.logging.backgroundprocess:
    image: microservice.logging.background
    container_name: microservice-logging-background
    build:
      context: .
      dockerfile: 02.CoreServices/Logging/Microservice.Logging.BackgroundProcess/Dockerfile

  ezstore.microservice.product.api:
    image: ezstore.product.api
    container_name: ezstore-product-api
    build:
      context: .
      dockerfile: 03.ezStore/Product/ezStore.Microservice.Product.API/Dockerfile
