version: '3.4'
    
services:
  identity-db:
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=IdentityServer
      - MYSQL_DATABASE=IdentityServer
    container_name: microservice.identity.db

  services-queue:
    build:
      context: .
      dockerfile: Dockerfile-RabbitMQ
    ports:
      - 15672:15672
    container_name: microservice.services.queue

  services-db:
    image: mongo:4.1.1
    ports:
      - 27017:27017
    container_name: microservice.services.db

  services-redis:
    image: redis:4.0.11
    ports:
      - 6379:6379
    container_name: microservice.services.redis